# Generated by Django 4.2.6 on 2023-10-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('board', models.JSONField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Ongoing', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='updated at')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Player name.', max_length=255)),
                ('symbol', models.CharField(help_text='Player symbol for a given game', max_length=1)),
                ('game_order', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second')], help_text='Order of the player in the game.')),
                ('game', models.ForeignKey(help_text='Game the player is playing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tic_tac_toe_api.game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='next_turn',
            field=models.ForeignKey(help_text='Player who will play next.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tic_tac_toe_api.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(help_text='Player who won the game.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='tic_tac_toe_api.player'),
        ),
    ]
