# Generated by Django 4.2.6 on 2023-10-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe_api', '0002_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='movements_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
